apiVersion: apps/v1
kind: Deployment
metadata:
  name: wloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wloud
  template:
    metadata:
      labels:
        app: wloud
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: wloud
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ecd14120-9da6-41ec-a0a7-0164beee2955"
        - name: Vless_Path
          value: "/MAKER"
        - name: Vmess_UUID
          value: "ecd14120-9da6-41ec-a0a7-0164beee2955"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
